#ifndef FUNCONFIG_H
#define FUNCONFIG_H

#define FUNCONF_SYSTICK_USE_HCLK 1

#define RV003USB_HID_FEATURES 1
#define RV003USB_SUPPORT_CONTROL_OUT 0
#define RV003USB_USE_REBOOT_FEATURE_REPORT 0
#define RV003USB_HANDLE_IN_REQUEST 0
#define RV003USB_HANDLE_USER_DATA 0
#define RV003USB_OTHER_CONTROL 0
#define RV003USB_EVENT_DEBUGGING 0
#define RV003USB_DEBUG_TIMING 0
#define RV003USB_CUSTOM_C 0
#define RV003USB_USB_TERMINAL 0
#define RV003USB_BOOTLOADER 0
#define RV003USB_OPTIMIZE_FLASH 1

#endif
